### ISSUE TITLE
DuckDb ConversionException when running MinHashLSH example

### ISSUE THREAD

**Issue by lmores** [NickCrews/mismo#45]
I am using Python 3.11.0 with `mismo` (from main [06c8f91](https://github.com/NickCrews/mismo/commit/06c8f91a2b83a93e9728fc159373cb8f1493b583)), `ibis-framework 9.1.0`, `duckdb 1.0.0`, `duckdb-engine 0.13.0`.

When running the [MinHashLSH example](https://nickcrews.github.io/mismo/howto/lsh/) on my computer I get the following error:

```txt
┌──────────┐
│ 10814709 │
└──────────┘
┏━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ record_id ┃ primaryTitle                                                            ┃ terms                      ┃ terms_filtered             ┃
┡━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ int64     │ string                                                                  │ array<string>              │ array<string>              │
├───────────┼─────────────────────────────────────────────────────────────────────────┼────────────────────────────┼────────────────────────────┤
│         0 │ Carmencita                                                              │ ['CARMENCITA']             │ ['CARMENCITA']             │
│         1 │ Le clown et ses chiens                                                  │ ['LE', 'CLOWN', ... +3]    │ ['LE', 'CLOWN', ... +3]    │
│         2 │ Pauvre Pierrot                                                          │ ['PAUVRE', 'PIERROT']      │ ['PAUVRE', 'PIERROT']      │
│         3 │ Un bon bock                                                             │ ['UN', 'BON', ... +1]      │ ['UN', 'BON', ... +1]      │
│         6 │ Corbett and Courtney Before the Kinetograph                             │ ['CORBETT', 'AND', ... +4] │ ['CORBETT', 'AND', ... +3] │
└───────────┴─────────────────────────────────────────────────────────────────────────┴────────────────────────────┴────────────────────────────┘
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "<OMISSIS>/batman.py", line 37, in <module>
    blocked = blocker(to_block, to_block)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<OMISSIS>/lib/python3.11/site-packages/mismo/block/_lsh.py", line 85, in __call__
    left = left.cache()
           ^^^^^^^^^^^^
  File "<OMISSIS>/lib/python3.11/site-packages/ibis/expr/types/relations.py", line 3619, in cache
    return current_backend._cached(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<OMISSIS>/lib/python3.11/site-packages/ibis/backends/__init__.py", line 1225, in _cached
    self._query_cache.store(expr)
  File "<OMISSIS>/lib/python3.11/site-packages/ibis/common/caching.py", line 75, in store
    self.populate(name, input)
  File "<OMISSIS>/lib/python3.11/site-packages/ibis/backends/duckdb/__init__.py", line 282, in _load_into_cache
    self.create_table(name, expr, schema=expr.schema(), temp=True)
  File "<OMISSIS>/lib/python3.11/site-packages/ibis/backends/duckdb/__init__.py", line 243, in create_table
    cur.execute(insert_stmt).fetchall()
    ^^^^^^^^^^^^^^^^^^^^^^^^
duckdb.duckdb.ConversionException: Conversion Error: Type INT64 with value -8494358239322671729 can't be cast because the value is out of range for the destination type UINT64
LINE 1: ...AS TINYINT)), __ibis_param_x__ -> CAST(CAST(CAST(HASH(__ibis_param_x__) AS BIT...
                                                  ^

```

Code:

```python
from __future__ import annotations

import ibis
from ibis import _

import mismo

ibis.options.interactive = True

t = ibis.examples.imdb_title_basics.fetch()
print(t.count())
t = t.head(1_000_000)

t = t.select(
    record_id=ibis.row_number(),
    primaryTitle=_.primaryTitle,
    terms=_.primaryTitle.upper().split(" "),
)
t = mismo.arrays.array_filter_isin_other(
    t, "terms", mismo.sets.rare_terms(t.terms, max_records_frac=0.05)
)
t = t.cache()
print(t.head())

# Performance is still very bad. For now filter to a smaller dataset.
# Hopefully we can keep the API something like this,
# but it may have to change to get the performance we need.
k = 5_000
batmans = t.filter(_.primaryTitle.upper().contains("BATMAN"))
to_block = ibis.union(batmans, t.head(k))

# The time required is related to the band size and number of bands,
# so keep them small as small as possible.
blocker = mismo.block.MinhashLshBlocker(
    terms_column="terms_filtered", band_size=5, n_bands=10
)
blocked = blocker(to_block, to_block)
blocked2 = blocked.filter(_.primaryTitle_l.upper() != _.primaryTitle_r.upper())
blocked2 = blocked2.cache()
print(blocked2.head())
```

**Comment by NickCrews** [comment]
I bet it is some change from ibis 9.1.0. if you `python -m pip install ibis==9.0.0` does the error still occur?

I should still fix mismo to be compatible with both, but that might be a workaround for you in the meantime.

**Comment by lmores** [comment]
Downgrading to ibis 9.0.0 solves the problem. Thank you! (sorry for the delayed follow up)

**Comment by lmores** [comment]
Just a remark that this is "officially" broken as we now depends on `ibis-framework>=9.1.0`.

**Comment by lmores** [comment]
So far I have just been playing/testing with the MinHashLSH blocker, therefore this is not a big problem for me (as far as the problem is limited to this class).
I posted my previous comment mostly because new people coming to try mismo may stop/abandon it if they try this out.

**Comment by NickCrews** [comment]
Thank you for the flag, I really appreciate it.

I just added a fix for this in https://github.com/NickCrews/mismo/commit/6f13e5daa2f4430efdb15c4f5d8a6852bf7a6d91.

Really, I need to add actual unit tests for this blocker so these regressions don't happen.
